name: Global CDN Purge Cache

on:
  push:
    branches:
      - master
    paths:
      - 'cdn/**'

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr Cache
        run: |
          curl -s https://purge.jsdelivr.net/gh/pavelzosim/atlas-framework@master/cdn/atlas-core.css
          curl -s https://purge.jsdelivr.net/gh/pavelzosim/atlas-framework@master/cdn/atlas-typography.css
